# Dependencies
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            David Myers
tagline:          blog
url:              http://david-myers.com
paginate:         1
baseurl:          /
author:
  name:           David Myers
  url:            http://david-myers.com
  email:          davidmyers9000@gmail.com

categories_path:  /portfolio

description: Web / Multimedia / iOS <br>Design <br>Development
gems:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          1.0.1
github:
  repo:           https://github.com/davidmyers9000/davidmyers9000.github.com
  resume:         http://resume.github.io/?davidmyers9000
  profile:        https://github.com/davidmyers9000
disqus:
  name:           dmyersblog
linkedin:         https://www.linkedin.com/in/dmyers9000