# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            David Myers
tagline:          blog 
url:              http://davidmyers9000.github.io
paginate:         1
baseurl:          /
author:
  name:           David Myers
  url:            http://david-myers.com
  email:          davidmyers9000@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/davidmyers9000/davidmyers9000.github.com
